"use client";

import { useState, useTransition } from "react";
import { deleteTransaction } from "@/actions/transaction.actions";
import { MoreHorizontal, Trash2, Edit } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { TransactionModal } from "@/components/dashboard/TransactionModal";

export function TransactionActionMenu({ transaction }: { transaction: any }) {
  const [pending, startTransition] = useTransition();
  const [isEditOpen, setIsEditOpen] = useState(false);

  const handleDelete = () => {
    if (confirm("Apakah Anda yakin ingin menghapus transaksi ini?")) {
      startTransition(async () => {
        await deleteTransaction(transaction.id);
      });
    }
  };

  // Jika ini otomatis dari penjualan (StokPOS), kita bisa larang edit/delete manual
  const isAutoGenerated = transaction.type === "PENJUALAN" || (transaction.type === "PENGELUARAN" && transaction.note?.includes("Kerugian stok rusak"));

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <button className="p-1.5 rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors text-zinc-400">
            <MoreHorizontal className="w-4 h-4" />
          </button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-32 bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800">
          {!isAutoGenerated && (
            <DropdownMenuItem
              onClick={() => setIsEditOpen(true)}
              className="cursor-pointer gap-2 focus:bg-indigo-50 dark:focus:bg-indigo-500/10 focus:text-indigo-600 dark:focus:text-indigo-400"
            >
              <Edit className="w-3.5 h-3.5" />
              Edit
            </DropdownMenuItem>
          )}
          
          <DropdownMenuItem
            onClick={handleDelete}
            disabled={pending}
            className="cursor-pointer gap-2 text-rose-600 focus:bg-rose-50 dark:focus:bg-rose-500/10 focus:text-rose-600"
          >
            <Trash2 className="w-3.5 h-3.5" />
            {pending ? "Menghapus..." : "Hapus"}
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      {/* Reusing Modal for Edit if needed */}
      {isEditOpen && (
        <TransactionModal initialData={transaction} forceOpen={isEditOpen} onForceClose={() => setIsEditOpen(false)} />
      )}
    </>
  );
}
